name: Simple Python Run

on:
  push:
    branches: [ main ]

jobs:
  run-python:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Python Script
      shell: cmd  
      run: python main.py