name: Run Python Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-python:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.10'
        
    - name: Display Python info
      run: |
        python --version
        pip --version
        
    - name: Run main Python script
      run: python main.py
      