name: Simple Python Run

on:
  push:
    branches: [ main ]

jobs:
  run-python:
    runs-on: [self-hosted]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Python Script
      run: python main.py
      
    - name: Show Results
      run: |
        cat success.txt || echo "No success file"
        ls -la